version: 2
sources:
  - name: raw
    database: KIWIMART2_DB
    schema: RAW
    tables:
    - name: customers
    - name: products
    - name: stores
    - name: inventory
    - name: orders      
      config:
        freshness:
          warn_after:
            count: 5
            period: minute
          # error_after:
          #   count: 10
          #   period: minute
        loaded_at_field: updated_at
    - name: order_items
    - name: orders_stream
    - name: order_items_stream